import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import ShopItem from '../components/Shop/ShopItem';
import Button from '../components/UI/Button';
import IconKaffeeTasse from '../components/Icons/IconKaffeeTasse';
import IconKaffeeSchaufel from '../components/Icons/IconKaffeeSchaufel';
import IconKaffeePflanze from '../components/Icons/IconKaffeePflanze';

import heroImage from '../public/img/FEND-Coffee-latte-art-3.png';
import shopImage from '../public/img/FEND-Coffee-shop.png';
import plantImage from '../public/img/FEND-coffee-plant.png';
import bagsImage from '../public/img/FEND-Coffee-bags-2.png';
import bagsLargeImage from '../public/img/FEND_Coffee_Costa-Rica 1.png';
import OpeningHours from '../components/Store/OpeningHours';
import Address from '../components/Store/Address';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Rustica</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className='font-roboto'>
                {/* hero section */}
                <section className='relative h-[75vh] min-h-[320px]'>
                    <div className='relative w-full h-full'>
                        <Image
                            src={heroImage}
                            alt='coffe latte art'
                            layout='fill'
                            objectFit='cover'
                            objectPosition='center'
                            priority
                        />
                    </div>
                    <div className='absolute bg-black/30 inset-0'>
                        <div className='flex flex-col justify-center items-center h-full'>
                            <h1 className='theme-text-h1-m text-white'>Rustica</h1>
                            <div className='theme-text-subh-m text-white'>
                                Bio und Fair seit 1991
                            </div>
                        </div>
                        <div className='relative bottom-[25%] flex justify-center'>
                            <Button label='zum Shop' anchor anchorId='#' />
                        </div>
                    </div>
                </section>
                <div className='spacer-lg' />
                {/* the caffee section */}
                <section>
                    <div className='cstm-container'>
                        <h2 className='theme-text-h2-m'>Rösterei & Café</h2>
                        <div className='spacer-sm' />
                        <p className='theme-text-body-m'>
                            Kaffee aus Kiel, direkt gehandelt und geröstet in der eigenen Rösterei,
                            serviert im gemütlichen Café in der Innenstadt.
                        </p>
                        <div className='spacer-sm' />
                        <div className='flex justify-between gap-10 theme-text-body-m'>
                            <Address />
                            <OpeningHours />
                        </div>
                        <div className='spacer-md' />
                        <div className='flex justify-end'>
                            <Image
                                src={shopImage}
                                height={182}
                                width={241}
                                alt='Our Coffee Shop with people enjoing our products.'
                            />
                        </div>
                    </div>
                </section>
                <div className='spacer-md' />
                {/* organic section */}
                <section>
                    <div className='cstm-container'>
                        <h2 className='theme-text-h3-m'>Bio und Fair</h2>
                        <div className='spacer-xs' />
                        <p className='theme-text-body-m'>
                            Weit hinten, hinter den Wortbergen, fern der Länder Vokalien und
                            Konsonantien leben die Blindtexte. Weit hinten, hinter den Wortbergen,
                            fern der Länder Vokalien und Konsonantien leben die Blindtexte. Und das
                            alles in bester Bio Qualität
                        </p>
                        <div className='spacer-md' />
                        <div>
                            <Image
                                src={plantImage}
                                height={160}
                                width={241}
                                alt='Our Coffee Shop with people enjoing our products.'
                            />
                        </div>
                    </div>
                </section>
                <div className='spacer-lg' />
                {/* shop section */}
                <section className='bg-theme-anthrazit text-theme-white'>
                    <div className='cstm-container'>
                        <div className='spacer-lg' />
                        <h2 className='theme-text-h2-m'>Entdecke unsere Kaffee Sorten</h2>
                        <div className='spacer-md' />
                        <div className='grid grid-cols-2-col-155px gap-x-[16px] gap-y-[40px] justify-center'>
                            <ShopItem />
                            <ShopItem />
                            <ShopItem />
                            <ShopItem />
                        </div>
                    </div>
                    <div className='spacer-md' />
                    <div className='flex justify-center'>
                        <Button label='alle Produkte' link href='#' borderWhite />
                    </div>
                    <div className='spacer-lg' />
                </section>

                {/* origin section */}
                <section className='relative h-[50vh] min-h-[320px]'>
                    <div className='relative w-full h-full'>
                        <Image
                            src={bagsImage}
                            alt='coffee bean bags'
                            layout='fill'
                            objectFit='cover'
                            objectPosition='center'
                            priority
                        />
                    </div>
                    <div className='absolute bg-black/30 inset-0'>
                        <div className='flex flex-col justify-center items-center h-full'>
                            <h1 className='theme-text-h3-m text-white'>Herkunft</h1>
                            <div className='spacer-xs' />
                            <p className='theme-text-body-m text-white w-[240px] md:w-[300px]'>
                                Weit hinten, hinter den Wortbergen, fern der Länder Vokalien und
                                Konsonantien leben die Blindtexte.Und das alles in bester Bio
                                Qualität
                            </p>
                            <div className='spacer-sm' />
                            <div className='theme-text-body-m text-white'>mehr</div>
                        </div>
                    </div>
                </section>

                {/* features section */}
                <section>
                    <div className='cstm-container'>
                        <div className='spacer-lg' />
                        <h2 className='theme-text-h2-m text-center'>Das steckt drin</h2>
                        <div className='spacer-md' />
                        <div>
                            <div className='flex justify-center'>
                                <Image
                                    src={bagsLargeImage}
                                    width='214'
                                    height='284'
                                    alt='Rustica coffe bag type Costa Rica'
                                />
                            </div>
                            <div className='spacer-md' />

                            <div className='flex flex-col items-center'>
                                <div className='flex gap-[60px]'>
                                    <div className='theme-text-body-m flex flex-col items-center text-center'>
                                        <IconKaffeeTasse width='45' height='46' />
                                        <div className='spacer-sm' />
                                        <div>{'Bester\nGeschmack'}</div>
                                    </div>
                                    <div className='theme-text-body-m flex flex-col items-center text-center'>
                                        <IconKaffeeSchaufel width='44' height='47' />
                                        <div className='spacer-sm' />
                                        <div>{'Fair\ngehandelt'}</div>
                                    </div>
                                    <div className='theme-text-body-m flex flex-col items-center text-center'>
                                        <IconKaffeePflanze width='44' height='48' />
                                        <div className='spacer-sm' />
                                        <div>{'Bio\nQualität'}</div>
                                    </div>
                                </div>
                                <div className='spacer-md' />
                                <div>
                                    <Button label='zum Shop' anchor anchorId='#' />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className='spacer-lg' />
                </section>

                {/* map section */}
                <section>
                    <div className='cstm-container'>
                        <div className='spacer-xs' />
                        <h2 className='theme-text-h2-m'>Komm vorbei</h2>
                        <div className='spacer-sm' />
                    </div>
                    <iframe
                        className='w-full h-[230px]'
                        src='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2325.855703782809!2d10.119832115979134!3d54.341858507377374!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47b2560c505797eb%3A0xf549da0f074162a9!2sFraunhoferstra%C3%9Fe%2013%2C%2024118%20Kiel!5e0!3m2!1sen!2sde!4v1641925286002!5m2!1sen!2sde'
                        frameBorder={0}
                        loading='lazy'
                        allowFullScreen
                    ></iframe>
                </section>
            </main>
        </div>
    );
};

export default Home;
